//*****************************************************************************
/*!
	\file xsi_random.h
	\brief CRandom class declaration.

	Copyright 2008 Autodesk, Inc.  All rights reserved.
	Use of this software is subject to the terms of the Autodesk license agreement
	provided at the time of installation or download, or which otherwise accompanies
	this software in either electronic or hard copy form.
*/
//*****************************************************************************

#if (_MSC_VER > 1000) || defined(SGI_COMPILER)
#pragma once
#endif

#ifndef __XSIRANDOM_H__
#define __XSIRANDOM_H__

#include "sicppsdk.h"
#include <math.h>

namespace XSI {

namespace MATH {

//*****************************************************************************
/*! \class CRandom xsi_random.h
	\idx random values:generator for C++ \endidx
	\brief A random number sequence generator class.

	If two instances of this class are created with the same seed, the exact same sequence of
	random numbers are generated by both objects.
	\since 8.0 (2010)
 */
//*****************************************************************************
class SICPPSDKDECL CRandom
{
	public:
	/*! Creates a new random generator based on a seed value of 0.
	*/
	SICPPSDK_INLINE CRandom();

	/*! Constructor. Creates a new random generator using the specified seed value.
	\param in_nSeed Initial seed value.
	*/
	SICPPSDK_INLINE CRandom( LONG in_nSeed );

	/*! Copy constructor. Creates a new random generator from an existing random generator.
	\param in_random CRandom object. The new object is initialized with the seed and current
	index from the source CRandom object.
	 */
	SICPPSDK_INLINE CRandom( const CRandom& in_random );

	/*! Destructor. */
	~CRandom() {}

	/*! Updates the seed value for this random generator object using the specified value.
	\param in_nSeed New seed value.
	*/
	SICPPSDK_INLINE void PutSeed( LONG in_nSeed );

	/*! Returns the sequence current value.
	\return The sequence current value.
	*/
	SICPPSDK_INLINE LONG GetValue() const;

	/*! Returns the sequence current value in the range of [0,1.0]
	\return float value.
	*/
	SICPPSDK_INLINE float GetNormalizedValue() const;

	/*! Returns the sequence current value.
	\return The sequence current value.
	*/
	SICPPSDK_INLINE operator LONG () const;

	/*! Set the sequence index to the specified index value.
	\param in_nIndex New index value.
	*/
	void PutIndex( ULONG in_nIndex );

	/*! Prefix increment operator. Sets the current sequence number to the next generated random value.
	\return The sequence next value.
	*/
	SICPPSDK_INLINE LONG operator++();

	/*! Postfix increment operator. Sets the current sequence number to the next generated random value.
	\return The sequence value prior to the operation.
	*/
	SICPPSDK_INLINE LONG operator++(int);

	/*! Prefix decrement operator. Sets the current sequence number to the previous sequence random value.
	\return The sequence previous value.
	*/
	SICPPSDK_INLINE LONG operator--();

	/*! Postfix decrement operator. Sets the current sequence number to the previous sequence random value.
	\return The sequence value prior the operation.
	*/
	SICPPSDK_INLINE LONG operator--(int);

	/*! Skips the specified number of elements in the sequence as specified by an offset.
	\param in_nOffset Number of elements to skip.
	*/
	SICPPSDK_INLINE void Skip( ULONG in_nOffset );

	private:
	void Init( LONG in_nSeed, short in_nState, ULONG in_nStartIndex );
	LONG GetValue( LONG in_nIndex ) const;
	LONG GetNext( LONG in_nPrev );
	LONG GetPrevious( LONG in_nNext );
	static LONG Skip( LONG in_nValue, ULONG in_nOffset );

	static ULONG Map( LONG in_nUnmapped );
	static LONG Unmap( ULONG in_nMapped );

	mutable enum State
	{
		HAVE_NONE,
		HAVE_INDEX,
		HAVE_INDEX_AND_RND
	} m_eState;

	LONG m_nSeed;
	ULONG m_nIndex;
	mutable LONG m_nRnd;
};

SICPPSDK_INLINE CRandom::CRandom()
{
	Init( 0, HAVE_NONE, 0 );
}

SICPPSDK_INLINE CRandom::CRandom( LONG in_nSeed )
{
	Init( in_nSeed, HAVE_NONE, 0 );
}

SICPPSDK_INLINE CRandom::CRandom( const CRandom& in_random )
{
	m_nSeed = in_random.m_nSeed;
	m_eState = in_random.m_eState;
	m_nIndex = in_random.m_nIndex;
	m_nRnd = in_random.m_nRnd;
}

SICPPSDK_INLINE void CRandom::PutSeed( LONG in_nSeed )
{
	m_nSeed = Map( 0 );
	PutIndex( in_nSeed + 12345 );
	m_nSeed = Map( GetValue() );
}

SICPPSDK_INLINE LONG CRandom::GetValue() const
{
	if ( m_eState < HAVE_INDEX_AND_RND )
	{
		m_nRnd = GetValue( m_nIndex );
		m_eState = HAVE_INDEX_AND_RND;
	}
	return m_nRnd;
}

SICPPSDK_INLINE float CRandom::GetNormalizedValue() const
{
	return (GetValue()/(float)(1<<30));
}

SICPPSDK_INLINE CRandom::operator LONG () const
{
	return GetValue();
}

SICPPSDK_INLINE LONG CRandom::operator++()
{
	++m_nIndex;
	if ( m_eState >= HAVE_INDEX_AND_RND )
	{
		return m_nRnd = GetNext( m_nRnd );
	}
	return GetValue();
}

SICPPSDK_INLINE LONG CRandom::operator++(int)
{
	++m_nIndex;
	int nTmp = GetValue();
	m_nRnd = GetNext( m_nRnd );
	return nTmp;
}

SICPPSDK_INLINE LONG CRandom::operator--()
{
	--m_nIndex;
	if ( m_eState >= HAVE_INDEX_AND_RND )
	{
		return m_nRnd = GetPrevious( m_nRnd );
	}

	return GetValue();
}

SICPPSDK_INLINE LONG CRandom::operator--(int)
{
	--m_nIndex;
	LONG nTmp = GetValue();
	m_nRnd = GetPrevious( m_nRnd );
	return nTmp;
}

SICPPSDK_INLINE void CRandom::Skip( ULONG in_nOffset )
{
	PutIndex( m_nIndex + in_nOffset );
}

};
};

#endif // __XSIRANDOM_H__
